language: ruby

rvm:
 - 2.2
 - 2.3
 - 2.4
 - 2.5
 - 2.6
 - 2.7

gemfile:
 - Gemfile

before_install: "gem update bundler"

script:
 - "bin/test"
 - "bundle exec rubocop"

notifications:
  email: false
